// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cibytrescwntdgxqjpfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYnl0cmVzY3dudGRneHFqcGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDM3MjYsImV4cCI6MjA2NDQ3OTcyNn0.Y1Z24F0OCKOzGG46zE0UNe-kAvVpq9-Mg_wVkw9F1-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);